services:
  backend:
    container_name: university-app
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: university-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: university-db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'