services:
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: kdb
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: db-kursach
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'