services:
  backend:
    container_name: university-app
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - kafka
  db:
    container_name: university-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: university-db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    platform: linux/arm64
    container_name: zookeeper
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    platform: linux/arm64
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: 'marks:3:1'