spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/university-db
    username: postgres
    password: postgres
  jooq:
    sql-dialect: postgres
  liquibase:
    enabled: false
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        partitioner.class: com.hulk.university.marks.MarkPartitioner
        spring:
          json.type.mapping: mark:com.hulk.university.tables.pojos.Mark
      retries: 2
  task:
    scheduling:
      pool:
        size: 2
springdoc:
  show-actuator: false
  api-docs:
    enabled: true
    version: openapi_3_1
  swagger-ui:
    enabled: true

app:
  system-user:
    enabled: true
    id: 0
    username: system
    password: "{bcrypt}$2a$12$/kb8lZm37GTuzu42z5hchOwechWP6Y1lFi1T6HECSpqik7YVfvHZi"
  security:
    jwt:
      secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
      time-to-live-in-seconds: 86400
  kafka:
    mark-topic-name: mark-topic
  scheduler:
    cron:
      interval: '0 */10 * * * *'
