spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db-kursach
    username: postgres
    password: postgres
  jooq:
    sql-dialect: postgres
  liquibase:
    enabled: false
springdoc:
  show-actuator: false
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
app:
  system-user:
    enabled: true
    id: 0
    username: system
    password: "{bcrypt}$2a$12$/kb8lZm37GTuzu42z5hchOwechWP6Y1lFi1T6HECSpqik7YVfvHZi"
  security:
    jwt:
      secret: YBBzRKQHxbAE98NyRGSDgBnDIFmFBEEv
      time-to-live-in-seconds: 86400
